### PR TITLE
Enable Travis CI builds

### PR DESCRIPTION
**Pull request by samtstern**
TODO:

- [x] Get admin rights and enable builds for this repo
- [x] Change encryption key not to point at my fork
- [x] Badge in README

### CODE REVIEW

**Comment by samtstern** [comment]
See #91

**Comment by samtstern** [comment]
We've got a green build!
https://travis-ci.org/samtstern/geofire-java/builds/308528746

**Comment by vanniktech** [comment]
Oh nice. It's not showing up on the PR checks though, any reason for that? Could also be that my mobile doesn't display it correctly.

**Comment by samtstern** [comment]
@vanniktech that's one of the TODOs.   I have commit rights on this repo but not admin rights so I can't add the travis webhooks and stuff yet.  The green build was from my fork.

**Comment by vanniktech** [comment]
Oh nice. It's not showing up on the PR checks though, any reason for that? Could also be that my mobile doesn't display it correctly.

**Comment by samtstern** [comment]
Just FYI the person who can make me admin on this repo is out on vacation so probably can't merge this till next week.

**Comment by vanniktech** [comment]
Alright that's cool. The badge is easy though:

`[Build Status](https://travis-ci.org/firebase/geofire-java?branch=master)`

**Pull request merged**
