### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jgarcia162**
fixed a typo

### CODE REVIEW

**Comment by jwngr** [comment]
Thanks for the typo fix! As per Google policy, you will need to sign the CLA in order to take any change, including one character ones like this. Please let us know once you've done that and we will get this merged in.

**Comment by jgarcia162** [comment]
I signed it!

JG

**Comment by jgarcia162** [comment]
CLA signed! Thanks.

JG

**Comment by jwngr** [comment]
Thanks for the PR!

**Pull request merged**
