### PR TITLE
Made location object creation from snapshot function public

### PR DESCRIPTION
**Pull request by jonahbron**
My particular application is watching location changes by location key, and querying for nearby locations.  The ability to take the snapshot from the query and directly convert that into a location object for the next query would be very handy.  This change makes that possible.

### CODE REVIEW

**Comment by samtstern** [comment]
@jwngr thoughts?  This does seem useful but I assume you had a reason for making this private in the first place.

**Comment by jwngr** [comment]
I'm a bit confused as to the exact use case. The intent of the library is to use a `GeoQuery`'s `onKeyEntered()` method to query for nearby locations. That listener returns the location is a digestible format, as can be seen in the example [here](https://github.com/firebase/geofire-java#receiving-events-for-geo-queries).

I guess I am not fully against making this public, but I would like to understand the use case more before we do that.

BTW @jdimond was the one who wrote this code, not me. He may have some opinion on the matter as well.

**Comment by jonahbron** [comment]
@jwngr Well, my intent was to have a bunch of users, each of which had a location attached to them.  The code was querying for users nearby to each other one, based on ID.  I wanted to query the location object directly to keep the GeoQuery up-to-date, but that didn't work, apparently because of a thread issue (https://github.com/firebase/geofire-java/issues/40).

So since that doesn't work, I guess my use-case for this has evaporated. If it's not possible to query the locations from the application in parallel with GeoFire, there's no real reason to need to perform that conversion. :cry:

**Comment by jonahbron** [comment]
Actually, my use-case is still valid.  I believe my app isn't working in AppEngine because of a bug (#40), not because of an inherent design flaw in my application.  Once that's fixed, my use-case will again be valid.

**Comment by samtstern** [comment]
@jonahbron looks like some of your AppEngine code got mixed up in this PR, is that intentional?

**Comment by jonahbron** [comment]
@samtstern Oops, my bad.  Let me fix that.

**Comment by jonahbron** [comment]
@samtstern Fixed.  Moved some stuff into the wrong branch.

**Comment by melashkov** [comment]
@jonahbron would you be able to squash commits?

**Comment by jonahbron** [comment]
@melashkov I could probably figure out how to do that, but I'm pretty sure you can choose that in Github when you merge.

**Comment by vanniktech** [comment]
Friendly ping here. @melashkov you can do this now with GitHub (Squash & merge)

**Comment by melashkov** [comment]
@anniktech I am not a awener of repo, cant merge 😢

**Comment by samtstern** [comment]
Thanks for the ping!  I will merge this now.

**Comment by vanniktech** [comment]
Could you also have a look at #76?

**Pull request merged**
