### PR TITLE
Simplify SimpleFuture. We only need a certain API and don't need to commit to the entire Future API.

### PR DESCRIPTION
**Pull request by vanniktech**
Part of #101

### CODE REVIEW

**Comment by vanniktech** [comment]
The build succeeded but it failed with `The command "./build.sh" exited with 1.`

**Comment by samtstern** [comment]
Wouldn't this be a breaking API change since folks may be using this with other utilities that accept `Future` for chaining/organization/etc?  I think having a standard API contract is a positive in that way, but curious as to why you think it's a negative.

**Comment by vanniktech** [comment]
As far as I understood this is only used when testing. If this type is public API (which I don't think it should) then I guess we're stuck with it.

Ideally I'd want this to be used only when testing though and also as minimal as possible. It's not worth having those other things implemented when only one of them is used.

**Comment by samtstern** [comment]
Hmm you're right it is only used in test ... but we have been exposing it in `com.firebase.geofire.core` as a public API.

I think we should probably move it to `test` if we're only using it there.  I am still conflicted though since doing so is **technically** a breaking API change even though we probably never intended for folks to rely on it.

**Comment by vanniktech** [comment]
Who would use that API though since it's not really exposed and just the class is hanging. I can certainly move it to `test` though.

**Comment by samtstern** [comment]
I am not a SemVer stickler and I think correcting this accidental API exposure can be corrected in a minor version.  Let's move it to `test` in this PR, thanks!

**Comment by samtstern** [comment]
@vanniktech thanks!  Let me try and see why the build is failing...

**Comment by samtstern** [comment]
You can try to merge in #105 (`master`) and see if the build goes green.

**Comment by samtstern** [comment]
Actually I can see in the Travis logs that this fine, merging!

**Pull request merged**
