### PR TITLE
Find radius with at least N results

### PR DESCRIPTION
**Pull request by RCasatta**
Iterative function for finding a radius that contain at least N results

### CODE REVIEW

**Comment by jwngr** [comment]
Hey @RCasatta - First off, thanks a lot for sending this PR. This is a question we get pretty often and it's awesome to see you take a crack at solving it. I talked with @jdimond (the author of `geofire-java`) and I think we both agree that this kind of functionality is not something which should belong in the core library. It is a bit too specific and also it is unclear how this should behave an new items are added to the query, in realtime. Does an item in the first N that gets pushed to position N+1 fire some sort of event indicating as much? What is that event called? We could reuse `onKeyExited()`, but the key is still technically within the query's radius, just not within its filter.

As a result, this is probably better suited as an example. If you want to update the PR to be a new example, we would gladly work with you to get it merged in. Otherwise, we will close this PR. Jonny can give a full code review of the actual code if you want to move forward with turning this into an example. Thanks again!

**Comment by RCasatta** [comment]
Hi Jacob,

i can modify this PR to become an example if you or @jdimond give me some directions.

However, i would to clarify two points.
* Like you said: "this is a question we get pretty often", so why aren't you answering in the library?
* I am not thinking about this functionality in term of a query filter, just a way to bootstrap the standard query. I think it's a common problem for a geolocation project that does not know before how many locations will be. 

I am not saying this PR implementation is a good, it's kinda hacky. I just think the problem it try to solve deserves more than an example but it is sure a good start.

Thanks

**Comment by jwngr** [comment]
Thanks for getting back to me. Let me try to comment on your good points.

I think one of the big roadblocks for me is something I mentioned in my last comment: how should this behave as new items are added to the query in realtime? Firing `onKeyExited()` as the top N items change seems like the most likely solution, but I'm not sure it fits in with how we are thinking about the current library. This probably requires some more design discussion.

Also, I think there are several ways to solve this problem, and the solution depends a bit on your use case. I think a generic solution for "find the N closest items" could cause poor performance for some use cases. For example, the optimal solution here is probably highly dependent on how many data points you have and how close together they are. I'm more inclined to provide a library which allows you implement whichever one you want (and provide examples for the different strategies) rather than providing a generic solution that won't work for everyone.

@jdimond - Can you provide a code review here and offer some pointers so we can turn this into an example? Also, if you disagree with what I said or want to offer some more opinions, go ahead.

**Comment by jdimond** [comment]
@RCasatta, sorry for the long delay, better late than never. I had a look at your code and there are a bunch of issues that I want to point out:
* The radius finder is blocking, which is general bad design because now you can't run it on the main thread without freezing up the UI.
* The way the algorithm works is very inefficient because it will create a bunch of queries under the hood. (which will all query Firebase) You should be able to reuse a single query and use `setRadius` for it to be a bit more efficient
* Catching exceptions instead of passing in valid parameters is in general not very good thing to do
* A lot of the code is not very idiomatic (using `Integer` objects instead of primitive types)
* There are a bunch of syntactic issues (tabs & spaces mixed, inconsistent parentheses, logging to system out, ...)

So at this time I don't think we can make this code an official example, so I'll close this issue. Let me know if you have any other questions.

**Pull request closed without merging**
