### PR TITLE
Make raisedEvent method public

### PR DESCRIPTION
**Pull request by adauvalter**
We extended GeoQuery class raising events from it. Right now it's impossible to due to access modifier.

### CODE REVIEW

**Comment by adauvalter** [comment]
I signed it!

**Comment by samtstern** [comment]
@adauvalter can you explain a little more about your use case here?

**Comment by adauvalter** [comment]
@samtstern the idea is, that we use a kind of cache on our side, to determine added, changed, removed points, because they're moving. Depends on the state we fire those events like `geoFire.raiseEvent { listener.objectMoved(it) }`

**Comment by vanniktech** [comment]
Our use case is also used [here](https://github.com/firebase/geofire-java/blob/8385c3148f816807ea3e1873c5e3772d76856057/src/main/java/com/firebase/geofire/GeoQuery.java) where the `raiseEvent` is called.

**Comment by vanniktech** [comment]
Just wanted to know whether there's an update on this. This is currently the only function that we need that is not public.

If this would get merged and a new release would be published, we could get rid of our internal fork.

In case you need any further explanation about the use case, let me know @samtstern

**Comment by samtstern** [comment]
@adauvalter @vanniktech as discussed (in person) at the Firebase Dev Summit, I am happy to merge this PR to make your use case easier.  I'll do it now!

I'd also love to hear more (if you have time) about the motivation for the PR and the ways you're customizing GeoFire.  Making this method public is sort of a hack, maybe a refactor would serve your needs better.

**Comment by samtstern** [comment]
Release `2.1.3`

**Comment by vanniktech** [comment]
Thanks for getting this in. As discussed, I emailed you with some personal information about our project and the requirements. I'm happy to translate the outputs of our discussion into issues / PRs.

**Pull request merged**
