### PR TITLE
Rename methods in GeoFireTestingRule.

### PR DESCRIPTION
**Pull request by vanniktech**
This should conclude #101

### CODE REVIEW

**Comment by samtstern** [comment]
Thanks for sending this!  Just FYI I'm on vacation this week without a
laptop so will review and merge next week when I'm back.

**Comment by vanniktech** [comment]
No worries. Enjoy your vacation ;)

**Comment by vanniktech** [comment]
@samtstern gentle push

**Comment by samtstern** [comment]
@vanniktech thanks for the reminder, I almost forgot.

**Pull request merged**
